/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ATM;

import View.Main.Trang_chu;
import dieu_khien.dieu_khien_atm;
import database.Card;
//import java.awt.Image;
//import java.io.File;
//import java.io.IOException;
import java.math.BigInteger;
import java.util.List;
//import javax.imageio.ImageIO;
//import javax.imageio.IIOException.rootnull;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class trang_banking extends javax.swing.JFrame {

    /**
     * Creates new form ATMGUI
     */
    public trang_banking() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ATM mô phỏng của Dương");
            /*Image image = null;
            try {
                File f = new File("logoBIDV.jpg");
                image = ImageIO.read(f);
            } catch (IOException ex) {
            }*/
        // Chút ý
        
    }
    
    public void getCardInfo(List<Card> listCard){
        lbFullName.setText("Xin chào "+listCard.get(0).getNameBoss());
        nameBoss = listCard.get(0).getNameBoss();
        cardID=listCard.get(0).getId();
    }
    
    public void viewBlance(){
        dieu_khien_atm a = new dieu_khien_atm();
        viewblace = new So_du(this,rootPaneCheckingEnabled);
        viewblace.getBlance(a.ViewBlance(cardID));
        viewblace.setVisible(true);
    }
    
    public BigInteger checkBlance() {
        dieu_khien_atm a = new dieu_khien_atm();
        return a.ViewBlance(cardID);
    }
 
    public void rutTien(BigInteger money){
        dieu_khien_atm atm = new dieu_khien_atm();
        if(atm.RutTien(cardID, money)){
            JOptionPane.showMessageDialog(this, "Rút tiền thành công !");
            withdraw.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Thất bại!");
            withdraw.dispose();
        }
    }
    
    public void changePin(int newpin){
        dieu_khien_atm atmc = new dieu_khien_atm();
        if(atmc.ChangePin(cardID, newpin)){
            JOptionPane.showMessageDialog(this, "Đổi mã pin thành công!");
            changePinDiaLog.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Đổi mã pin thất bại!");
        }
    }
     
    public void transferMoney(BigInteger receiver_cardID, BigInteger money){
        dieu_khien_atm atmc = new dieu_khien_atm();
        String note = nameBoss+" chuyen khoan";
        if(atmc.Transfer(cardID, receiver_cardID, money, note)){
            JOptionPane.showMessageDialog(this, "Chuyển khoản thành công.");
            transfer.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Chuyển khoản thất bại!");
        }
// thằng quang ngu vlllll
        
    }
    
    public void ViewHistoryTransaction() {
        dieu_khien_atm a = new dieu_khien_atm();
        transactionHistory = new lich_su_chuyen_tien(this, rootPaneCheckingEnabled);
        transactionHistory.getHistoryTransaction(a.ViewHistoryTransaction(cardID));
        transactionHistory.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn3 = new javax.swing.JPanel();
        lbFullName = new javax.swing.JLabel();
        btnRutTien = new javax.swing.JButton();
        btnViewBlane = new javax.swing.JButton();
        btnChangPin = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFullName.setText("Xin chào");

        btnRutTien.setText("Rút tiền");
        btnRutTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutTienActionPerformed(evt);
            }
        });

        btnViewBlane.setText("Vấn tin tài khoản");
        btnViewBlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBlaneActionPerformed(evt);
            }
        });

        btnChangPin.setText("Đổi PIN");
        btnChangPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangPinActionPerformed(evt);
            }
        });

        btnTransfer.setText("Chuyển khoản");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnHistory.setText("Lịch sử GD");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn3Layout = new javax.swing.GroupLayout(pn3);
        pn3.setLayout(pn3Layout);
        pn3Layout.setHorizontalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRutTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewBlane, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pn3Layout.setVerticalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRutTien, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btnViewBlane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChangPin, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("back ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        // TODO add your handling code here:
          transfer = new Chuyển_khoản_nè(this, rootPaneCheckingEnabled);

          transfer.setVisible(true);//chú ý tính năng này là chuyển khoản
         
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnViewBlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBlaneActionPerformed
        // TODO add your handling code here:
        viewBlance();
    }//GEN-LAST:event_btnViewBlaneActionPerformed

    private void btnRutTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutTienActionPerformed
        // TODO add your handling code here:
        withdraw  = new rut_tien(this, rootPaneCheckingEnabled);
        withdraw.setVisible(true);
        
    }//GEN-LAST:event_btnRutTienActionPerformed

    private void btnChangPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangPinActionPerformed
        // TODO add your handling code here:
        changePinDiaLog = new Doi_ma_pin(this, rootPaneCheckingEnabled);
        changePinDiaLog.setVisible(true);
        
    }//GEN-LAST:event_btnChangPinActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        ViewHistoryTransaction();
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        Trang_chu nm = new Trang_chu();
        nm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private So_du viewblace;
    private BigInteger cardID;
    private String nameBoss;
    private rut_tien withdraw;
    private Doi_ma_pin changePinDiaLog;
    private Chuyển_khoản_nè transfer;
    private  lich_su_chuyen_tien transactionHistory;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangPin;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnRutTien;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnViewBlane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JPanel pn3;
    // End of variables declaration//GEN-END:variables
}
